name       : hyphen-es
version    : '2.6'
release    : 1
source     :
    - https://github.com/sbosio/rla-es/releases/download/v2.6/es.oxt : 10fa51dffb78f0fc15fd791770813f551da43cf007b52cb8fb6ccb0b4117e85f
homepage   : https://github.com/sbosio/rla-es/tree/master/separacion
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MPL-1.1
component  : office.spelling
summary    : Spanish hyphenation rules
description: |
    Spanish hyphenation rules.
rundeps    :
    - hyphen
install    : |
    install -Dm00644 hyph_es.dic $installdir/usr/share/hyphen/hyph_es.dic

    pushd $installdir/usr/share/hyphen
        es_aliases="es_AR es_BO es_CL es_CO es_CR es_CU es_DO es_EC es_ES es_GQ es_GT es_HN es_MX es_NI es_PA es_PE es_PH es_PR es_PY es_SV es_US es_UY es_VE"
        for lang in $es_aliases; do
            ln -s hyph_es.dic hyph_$lang.dic
        done
    popd
